name: Run schedule tests

on:
  workflow_dispatch:

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Install Dependencies and library
        shell: bash
        run: |
          set -ux
          uv pip install --system .[lint]

      - name: Run ruff
        shell: bash
        run: ruff check

      - name: Run mypy
        shell: bash
        run: mypy

      - name: Run bandit
        shell: bash
        run: bandit -c pyproject.toml -r chat

      - name: Run Semgrep
        shell: bash
        run: semgrep scan --config auto --error
        
  test-basic:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4

        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Install Dependencies
        run: uv pip install --system .[testing]

      - name: Run pytest
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        run: pytest -q
